/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  syncEndpoint: "http://localhost:3001/api/sync",
  webhookSecret: ""
};
var SyncPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    const ribbonIconEl = this.addRibbonIcon("refresh-cw", "VermilionVoid: Trigger Sync", (evt) => {
      this.triggerSync();
    });
    this.addCommand({
      id: "trigger-vermilion-void-sync",
      name: "Trigger Blog Sync",
      callback: () => {
        this.triggerSync();
      }
    });
    this.addSettingTab(new SyncSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async triggerSync() {
    if (!this.settings.syncEndpoint) {
      new import_obsidian.Notice("Error: Sync endpoint is not configured in settings.");
      return;
    }
    new import_obsidian.Notice("Sync starting...");
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: this.settings.syncEndpoint,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${this.settings.webhookSecret}`
        }
      });
      if (response.status === 202 || response.status === 200) {
        new import_obsidian.Notice("Sync successfully triggered! Go backend is processing.");
      } else {
        new import_obsidian.Notice(`Sync failed (Status ${response.status}): ${response.text}`);
      }
    } catch (error) {
      console.error("VermilionVoid Sync Error:", error);
      new import_obsidian.Notice(`Sync failed: ${error.message}`);
    }
  }
};
var SyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "VermilionVoid Sync Settings" });
    new import_obsidian.Setting(containerEl).setName("Sync Endpoint").setDesc("The URL of your Go sync server /api/sync endpoint.").addText((text) => text.setPlaceholder("http://your-server:3001/api/sync").setValue(this.plugin.settings.syncEndpoint).onChange(async (value) => {
      this.plugin.settings.syncEndpoint = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Webhook Secret").setDesc("The secret key (Bearer token) configured in your server's .env file.").addText((text) => text.setPlaceholder("Enter your secret").setValue(this.plugin.settings.webhookSecret).onChange(async (value) => {
      this.plugin.settings.webhookSecret = value;
      await this.plugin.saveSettings();
    }));
  }
};
